In [78]:
import numpy as np
from itertools import product


In [79]:
h = np.load('h_5_5.npy')
print(h)

[[0.15005067 0.61103358 0.71358537 0.41028108 0.73298685]
 [0.92085189 0.02754327 0.43298144 0.67761797 0.7430438 ]
 [0.98877682 0.88635377 0.82531773 0.58600132 0.63754181]
 [0.08416054 0.57826972 0.5752686  0.22545874 0.32396492]
 [0.0883358  0.93502254 0.51214525 0.30915861 0.025513  ]]


In [80]:
def compute_energy(h, config, J=1):
    n, m = h.shape
    energy = 0

    # Compute interaction energy with periodic boundaries
    for i in range(n):
        for j in range(m):
            s = config[i, j]
            # Consider only "right" and "down" neighbors to avoid double counting
            neighbors = [
                config[(i + 1) % n, j],  # Down
                config[i, (j + 1) % m]   # Right
            ]
            energy -= J * s * sum(neighbors)
    
    # Compute interaction with the external magnetic field
    energy -= np.sum(h * config)
    return energy


In [81]:
def all_possible_energies(field, J=1):
    n, m = field.shape
    num_sites = n * m

    # Generate all possible configurations
    energies = {}
    for binary_config in product([1, -1], repeat=num_sites):
        config = np.array(binary_config).reshape((n, m))
        energy = compute_energy(h, config, J)
        energies[energy] = config
    
    return energies

In [ ]:
energies = all_possible_energies(h)
min_energy = min(energies.keys())
min_energy_config = energies[min_energy]
print(min_energy_config)
print(min_energy)