In [5]:
import numpy as np
from itertools import product
import time

In [6]:
h = np.load('data/h_4_4.npy')
#h = np.array([[-0.42900093, -0.34531477], [-0.1746655, -0.28350231]])
J = 0.3

In [7]:
def qubit_idx(i, j, n_cols):
    return i * n_cols + j

In [8]:
import numpy as np

def compute_energy(h, config, J=1):
    n, m = h.shape

    # Shift configurations to compute interactions
    down_interaction = config[:-1, :] * config[1:, :]  # Down neighbors
    right_interaction = config[:, :-1] * config[:, 1:]  # Right neighbors

    # Compute energy contributions from interactions
    interaction_energy = -J * (np.sum(down_interaction) + np.sum(right_interaction))

    # Compute energy contributions from the external field
    field_energy = -np.sum(h * config)

    return interaction_energy + field_energy


In [9]:
def all_possible_energies(field, J=1):
    n, m = field.shape
    num_sites = n * m

    # Generate all possible configurations
    energies = {}
    for binary_config in product([1, -1], repeat=num_sites):
        config = np.array(binary_config).reshape((n, m))
        energy = compute_energy(h, config, J)
        energies[energy] = config
    
    return energies

In [10]:
start_time = time.time()
energies = all_possible_energies(h, J=J)
end_time = time.time()
min_energy = min(energies.keys())
min_energy_config = energies[min_energy]
print(min_energy_config)
print(min_energy)
print(energies)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
-10.333169515182433


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [11]:
print(f"Execution time: {end_time - start_time:.6f} seconds")

Execution time: 0.556237 seconds


In [12]:
# Testing below

In [13]:
#configuration = np.array([[-1, 1, -1], [-1, -1, -1], [-1, -1, -1]])
c = np.array([[ 1,  1, -1, -1,  1],
 [ 1, -1, -1, -1,  1],
 [-1,  1, -1,  1,  1],
 [-1, -1, -1, -1,  1],
 [-1, -1, -1, -1, -1]]

)
#configuration = np.array([[1, -1, 1, -1], [-1, 1, -1, 1], [1, -1, 1, -1], [-1, 1, -1, 1]])
#c = np.ones((5,5))
h = c * .01
h3 = np.load("h_5_5.npy")
#print(compute_energy2(h, c, J=1))

print(compute_energy20(h3, c, J=1.0))
#print(calculate_ising_energy(configuration, -1.0, h, False))

FileNotFoundError: [Errno 2] No such file or directory: 'h_5_5.npy'